### ISSUE TITLE
Are docs outdated or am i missing something?

### ISSUE THREAD

**Issue by halilibrahim** [apollographql/angular-docs#69]
Hi,
For example according to [this section](https://github.com/apollographql/angular-docs/blob/master/source/queries.md#using-with-rxjs) we should be able to use watchQuery as ApolloQueryObservable. But watchQuery returns ObservableQuery not ApolloQueryObservable.
Also watchQuery doesn't have a subscribe method as shown in [basic queries](https://github.com/apollographql/angular-docs/blob/master/source/queries.md#basic-queries) section.

**Comment by stubailo** [comment]
They redirect now to the new docs, thanks for reporting! Here's the new page: https://www.apollographql.com/docs/angular/basics/queries.html
